### ISSUE TITLE
Crash in Example Code

### ISSUE THREAD

**Issue by SinghAmitt** [reejosamuel/RSA#3]
The current example application crashes at line 470 of class RSA.m while trying to decrypt after a key pair was generated.

**Comment by SinghAmitt** [comment]
Also, the private key fails to decrypt the data previously encrypted with the public key. The key pair was generated using  - 

        [rsa generateKeyPairRSACompleteBlock:^{
        
        NSString *pubKey= [rsa getPublicKeyAsBase64ForJavaServer];
        
         privateKey = [rsa getPrivateKeyAsBase64ForJavaServer];

and I am trying the encrypt and decrypt operations in the following manner : 

       encWithPubKey = [RAS encryptString:@"Hello Amit Thakur Hello Amit" publicKey:pubKey];
      
        NSString *str=[RAS decryptString:encWithPubKey privateKey:privateKey];

**Comment by reejosamuel** [comment]
I updated the project and retested. If the crash is still happening please post here and also I might require some (throw-away) sample keys.

Sorry for the late response, since I had stopped working on crypto it was hard to fix bugs at the time of your issue.
